# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers

class PlainLabelMeta(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsPlainLabelMeta(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PlainLabelMeta()
        x.Init(buf, n + offset)
        return x

    # PlainLabelMeta
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PlainLabelMeta
    def NumClasses(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def PlainLabelMetaStart(builder): builder.StartObject(1)
def PlainLabelMetaAddNumClasses(builder, numClasses): builder.PrependInt32Slot(0, numClasses, 0)
def PlainLabelMetaEnd(builder): return builder.EndObject()
