# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers

class PlainLabel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsPlainLabel(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PlainLabel()
        x.Init(buf, n + offset)
        return x

    # PlainLabel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PlainLabel
    def LabelContent(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # PlainLabel
    def LabelContentAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # PlainLabel
    def LabelContentLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def PlainLabelStart(builder): builder.StartObject(1)
def PlainLabelAddLabelContent(builder, labelContent): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(labelContent), 0)
def PlainLabelStartLabelContentVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def PlainLabelEnd(builder): return builder.EndObject()
