# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers

class PredictLocationsConfigs(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsPredictLocationsConfigs(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PredictLocationsConfigs()
        x.Init(buf, n + offset)
        return x

    # PredictLocationsConfigs
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PredictLocationsConfigs
    def DatasetDir(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PredictLocationsConfigs
    def DecDatasetDir(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PredictLocationsConfigs
    def NetworkArchPath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PredictLocationsConfigs
    def WeightsLoadDir(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PredictLocationsConfigs
    def PredsSaveDir(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PredictLocationsConfigs
    def SnapshotDir(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PredictLocationsConfigs
    def ClientPkSigFile(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PredictLocationsConfigs
    def SgxSkSigFile(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PredictLocationsConfigs
    def SgxPkSigFile(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PredictLocationsConfigs
    def SignedTaskConfigPath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PredictLocationsConfigs
    def ClientAesGcmKeyFile(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PredictLocationsConfigs
    def SgxAesGcmKeyFile(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def PredictLocationsConfigsStart(builder): builder.StartObject(12)
def PredictLocationsConfigsAddDatasetDir(builder, datasetDir): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(datasetDir), 0)
def PredictLocationsConfigsAddDecDatasetDir(builder, decDatasetDir): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(decDatasetDir), 0)
def PredictLocationsConfigsAddNetworkArchPath(builder, networkArchPath): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(networkArchPath), 0)
def PredictLocationsConfigsAddWeightsLoadDir(builder, weightsLoadDir): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(weightsLoadDir), 0)
def PredictLocationsConfigsAddPredsSaveDir(builder, predsSaveDir): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(predsSaveDir), 0)
def PredictLocationsConfigsAddSnapshotDir(builder, snapshotDir): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(snapshotDir), 0)
def PredictLocationsConfigsAddClientPkSigFile(builder, clientPkSigFile): builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(clientPkSigFile), 0)
def PredictLocationsConfigsAddSgxSkSigFile(builder, sgxSkSigFile): builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(sgxSkSigFile), 0)
def PredictLocationsConfigsAddSgxPkSigFile(builder, sgxPkSigFile): builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(sgxPkSigFile), 0)
def PredictLocationsConfigsAddSignedTaskConfigPath(builder, signedTaskConfigPath): builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(signedTaskConfigPath), 0)
def PredictLocationsConfigsAddClientAesGcmKeyFile(builder, clientAesGcmKeyFile): builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(clientAesGcmKeyFile), 0)
def PredictLocationsConfigsAddSgxAesGcmKeyFile(builder, sgxAesGcmKeyFile): builder.PrependUOffsetTRelativeSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(sgxAesGcmKeyFile), 0)
def PredictLocationsConfigsEnd(builder): return builder.EndObject()
