# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers

class SingleUnitParamSet(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsSingleUnitParamSet(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SingleUnitParamSet()
        x.Init(buf, n + offset)
        return x

    # SingleUnitParamSet
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SingleUnitParamSet
    def ParamContent(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # SingleUnitParamSet
    def ParamContentAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # SingleUnitParamSet
    def ParamContentLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def SingleUnitParamSetStart(builder): builder.StartObject(1)
def SingleUnitParamSetAddParamContent(builder, paramContent): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(paramContent), 0)
def SingleUnitParamSetStartParamContentVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def SingleUnitParamSetEnd(builder): return builder.EndObject()
