// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_AES128CTR_H_
#define FLATBUFFERS_GENERATED_AES128CTR_H_

#include "flatbuffers/flatbuffers.h"

struct AESCTR128Enc;
struct AESCTR128EncT;

inline const flatbuffers::TypeTable *AESCTR128EncTypeTable();

struct AESCTR128EncT : public flatbuffers::NativeTable {
  typedef AESCTR128Enc TableType;
  std::vector<uint8_t> enc_content;
  std::vector<int8_t> iv;
  AESCTR128EncT() {
  }
};

struct AESCTR128Enc FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef AESCTR128EncT NativeTableType;
  static const flatbuffers::TypeTable *MiniReflectTypeTable() {
    return AESCTR128EncTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ENC_CONTENT = 4,
    VT_IV = 6
  };
  const flatbuffers::Vector<uint8_t> *enc_content() const {
    return GetPointer<const flatbuffers::Vector<uint8_t> *>(VT_ENC_CONTENT);
  }
  flatbuffers::Vector<uint8_t> *mutable_enc_content() {
    return GetPointer<flatbuffers::Vector<uint8_t> *>(VT_ENC_CONTENT);
  }
  const flatbuffers::Vector<int8_t> *iv() const {
    return GetPointer<const flatbuffers::Vector<int8_t> *>(VT_IV);
  }
  flatbuffers::Vector<int8_t> *mutable_iv() {
    return GetPointer<flatbuffers::Vector<int8_t> *>(VT_IV);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_ENC_CONTENT) &&
           verifier.VerifyVector(enc_content()) &&
           VerifyOffsetRequired(verifier, VT_IV) &&
           verifier.VerifyVector(iv()) &&
           verifier.EndTable();
  }
  AESCTR128EncT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(AESCTR128EncT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<AESCTR128Enc> Pack(flatbuffers::FlatBufferBuilder &_fbb, const AESCTR128EncT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct AESCTR128EncBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_enc_content(flatbuffers::Offset<flatbuffers::Vector<uint8_t>> enc_content) {
    fbb_.AddOffset(AESCTR128Enc::VT_ENC_CONTENT, enc_content);
  }
  void add_iv(flatbuffers::Offset<flatbuffers::Vector<int8_t>> iv) {
    fbb_.AddOffset(AESCTR128Enc::VT_IV, iv);
  }
  explicit AESCTR128EncBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  AESCTR128EncBuilder &operator=(const AESCTR128EncBuilder &);
  flatbuffers::Offset<AESCTR128Enc> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<AESCTR128Enc>(end);
    fbb_.Required(o, AESCTR128Enc::VT_ENC_CONTENT);
    fbb_.Required(o, AESCTR128Enc::VT_IV);
    return o;
  }
};

inline flatbuffers::Offset<AESCTR128Enc> CreateAESCTR128Enc(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<uint8_t>> enc_content = 0,
    flatbuffers::Offset<flatbuffers::Vector<int8_t>> iv = 0) {
  AESCTR128EncBuilder builder_(_fbb);
  builder_.add_iv(iv);
  builder_.add_enc_content(enc_content);
  return builder_.Finish();
}

inline flatbuffers::Offset<AESCTR128Enc> CreateAESCTR128EncDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint8_t> *enc_content = nullptr,
    const std::vector<int8_t> *iv = nullptr) {
  auto enc_content__ = enc_content ? _fbb.CreateVector<uint8_t>(*enc_content) : 0;
  auto iv__ = iv ? _fbb.CreateVector<int8_t>(*iv) : 0;
  return CreateAESCTR128Enc(
      _fbb,
      enc_content__,
      iv__);
}

flatbuffers::Offset<AESCTR128Enc> CreateAESCTR128Enc(flatbuffers::FlatBufferBuilder &_fbb, const AESCTR128EncT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline AESCTR128EncT *AESCTR128Enc::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  auto _o = new AESCTR128EncT();
  UnPackTo(_o, _resolver);
  return _o;
}

inline void AESCTR128Enc::UnPackTo(AESCTR128EncT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = enc_content(); if (_e) { _o->enc_content.resize(_e->size()); for (flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->enc_content[_i] = _e->Get(_i); } } }
  { auto _e = iv(); if (_e) { _o->iv.resize(_e->size()); for (flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->iv[_i] = _e->Get(_i); } } }
}

inline flatbuffers::Offset<AESCTR128Enc> AESCTR128Enc::Pack(flatbuffers::FlatBufferBuilder &_fbb, const AESCTR128EncT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateAESCTR128Enc(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<AESCTR128Enc> CreateAESCTR128Enc(flatbuffers::FlatBufferBuilder &_fbb, const AESCTR128EncT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const AESCTR128EncT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _enc_content = _fbb.CreateVector(_o->enc_content);
  auto _iv = _fbb.CreateVector(_o->iv);
  return CreateAESCTR128Enc(
      _fbb,
      _enc_content,
      _iv);
}

inline const flatbuffers::TypeTable *AESCTR128EncTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_UCHAR, 1, -1 },
    { flatbuffers::ET_CHAR, 1, -1 }
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_TABLE, 2, type_codes, nullptr, nullptr, nullptr
  };
  return &tt;
}

inline const AESCTR128Enc *GetAESCTR128Enc(const void *buf) {
  return flatbuffers::GetRoot<AESCTR128Enc>(buf);
}

inline const AESCTR128Enc *GetSizePrefixedAESCTR128Enc(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<AESCTR128Enc>(buf);
}

inline AESCTR128Enc *GetMutableAESCTR128Enc(void *buf) {
  return flatbuffers::GetMutableRoot<AESCTR128Enc>(buf);
}

inline bool VerifyAESCTR128EncBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<AESCTR128Enc>(nullptr);
}

inline bool VerifySizePrefixedAESCTR128EncBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<AESCTR128Enc>(nullptr);
}

inline void FinishAESCTR128EncBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<AESCTR128Enc> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedAESCTR128EncBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<AESCTR128Enc> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<AESCTR128EncT> UnPackAESCTR128Enc(
    const void *buf,
    const flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<AESCTR128EncT>(GetAESCTR128Enc(buf)->UnPack(res));
}

inline std::unique_ptr<AESCTR128EncT> UnPackSizePrefixedAESCTR128Enc(
    const void *buf,
    const flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<AESCTR128EncT>(GetSizePrefixedAESCTR128Enc(buf)->UnPack(res));
}

#endif  // FLATBUFFERS_GENERATED_AES128CTR_H_
