// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_AES128CTR_H_
#define FLATBUFFERS_GENERATED_AES128CTR_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 22 &&
              FLATBUFFERS_VERSION_MINOR == 11 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

struct AESCTR128Enc;
struct AESCTR128EncBuilder;

struct AESCTR128Enc FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef AESCTR128EncBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ENC_CONTENT = 4,
    VT_IV = 6
  };
  const flatbuffers::Vector<uint8_t> *enc_content() const {
    return GetPointer<const flatbuffers::Vector<uint8_t> *>(VT_ENC_CONTENT);
  }
  flatbuffers::Vector<uint8_t> *mutable_enc_content() {
    return GetPointer<flatbuffers::Vector<uint8_t> *>(VT_ENC_CONTENT);
  }
  const flatbuffers::Vector<int8_t> *iv() const {
    return GetPointer<const flatbuffers::Vector<int8_t> *>(VT_IV);
  }
  flatbuffers::Vector<int8_t> *mutable_iv() {
    return GetPointer<flatbuffers::Vector<int8_t> *>(VT_IV);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_ENC_CONTENT) &&
           verifier.VerifyVector(enc_content()) &&
           VerifyOffsetRequired(verifier, VT_IV) &&
           verifier.VerifyVector(iv()) &&
           verifier.EndTable();
  }
};

struct AESCTR128EncBuilder {
  typedef AESCTR128Enc Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_enc_content(flatbuffers::Offset<flatbuffers::Vector<uint8_t>> enc_content) {
    fbb_.AddOffset(AESCTR128Enc::VT_ENC_CONTENT, enc_content);
  }
  void add_iv(flatbuffers::Offset<flatbuffers::Vector<int8_t>> iv) {
    fbb_.AddOffset(AESCTR128Enc::VT_IV, iv);
  }
  explicit AESCTR128EncBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<AESCTR128Enc> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<AESCTR128Enc>(end);
    fbb_.Required(o, AESCTR128Enc::VT_ENC_CONTENT);
    fbb_.Required(o, AESCTR128Enc::VT_IV);
    return o;
  }
};

inline flatbuffers::Offset<AESCTR128Enc> CreateAESCTR128Enc(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<uint8_t>> enc_content = 0,
    flatbuffers::Offset<flatbuffers::Vector<int8_t>> iv = 0) {
  AESCTR128EncBuilder builder_(_fbb);
  builder_.add_iv(iv);
  builder_.add_enc_content(enc_content);
  return builder_.Finish();
}

inline flatbuffers::Offset<AESCTR128Enc> CreateAESCTR128EncDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint8_t> *enc_content = nullptr,
    const std::vector<int8_t> *iv = nullptr) {
  auto enc_content__ = enc_content ? _fbb.CreateVector<uint8_t>(*enc_content) : 0;
  auto iv__ = iv ? _fbb.CreateVector<int8_t>(*iv) : 0;
  return CreateAESCTR128Enc(
      _fbb,
      enc_content__,
      iv__);
}

inline const AESCTR128Enc *GetAESCTR128Enc(const void *buf) {
  return flatbuffers::GetRoot<AESCTR128Enc>(buf);
}

inline const AESCTR128Enc *GetSizePrefixedAESCTR128Enc(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<AESCTR128Enc>(buf);
}

inline AESCTR128Enc *GetMutableAESCTR128Enc(void *buf) {
  return flatbuffers::GetMutableRoot<AESCTR128Enc>(buf);
}

inline AESCTR128Enc *GetMutableSizePrefixedAESCTR128Enc(void *buf) {
  return flatbuffers::GetMutableSizePrefixedRoot<AESCTR128Enc>(buf);
}

inline bool VerifyAESCTR128EncBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<AESCTR128Enc>(nullptr);
}

inline bool VerifySizePrefixedAESCTR128EncBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<AESCTR128Enc>(nullptr);
}

inline void FinishAESCTR128EncBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<AESCTR128Enc> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedAESCTR128EncBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<AESCTR128Enc> root) {
  fbb.FinishSizePrefixed(root);
}

#endif  // FLATBUFFERS_GENERATED_AES128CTR_H_
