// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PLAINIMAGELABEL_H_
#define FLATBUFFERS_GENERATED_PLAINIMAGELABEL_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 22 &&
              FLATBUFFERS_VERSION_MINOR == 11 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

struct PlainImageLabel;
struct PlainImageLabelBuilder;

struct PlainImageLabel FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef PlainImageLabelBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_IMG_CONTENT = 4,
    VT_LABEL_CONTENT = 6
  };
  const flatbuffers::Vector<float> *img_content() const {
    return GetPointer<const flatbuffers::Vector<float> *>(VT_IMG_CONTENT);
  }
  flatbuffers::Vector<float> *mutable_img_content() {
    return GetPointer<flatbuffers::Vector<float> *>(VT_IMG_CONTENT);
  }
  const flatbuffers::Vector<float> *label_content() const {
    return GetPointer<const flatbuffers::Vector<float> *>(VT_LABEL_CONTENT);
  }
  flatbuffers::Vector<float> *mutable_label_content() {
    return GetPointer<flatbuffers::Vector<float> *>(VT_LABEL_CONTENT);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_IMG_CONTENT) &&
           verifier.VerifyVector(img_content()) &&
           VerifyOffsetRequired(verifier, VT_LABEL_CONTENT) &&
           verifier.VerifyVector(label_content()) &&
           verifier.EndTable();
  }
};

struct PlainImageLabelBuilder {
  typedef PlainImageLabel Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_img_content(flatbuffers::Offset<flatbuffers::Vector<float>> img_content) {
    fbb_.AddOffset(PlainImageLabel::VT_IMG_CONTENT, img_content);
  }
  void add_label_content(flatbuffers::Offset<flatbuffers::Vector<float>> label_content) {
    fbb_.AddOffset(PlainImageLabel::VT_LABEL_CONTENT, label_content);
  }
  explicit PlainImageLabelBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<PlainImageLabel> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<PlainImageLabel>(end);
    fbb_.Required(o, PlainImageLabel::VT_IMG_CONTENT);
    fbb_.Required(o, PlainImageLabel::VT_LABEL_CONTENT);
    return o;
  }
};

inline flatbuffers::Offset<PlainImageLabel> CreatePlainImageLabel(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<float>> img_content = 0,
    flatbuffers::Offset<flatbuffers::Vector<float>> label_content = 0) {
  PlainImageLabelBuilder builder_(_fbb);
  builder_.add_label_content(label_content);
  builder_.add_img_content(img_content);
  return builder_.Finish();
}

inline flatbuffers::Offset<PlainImageLabel> CreatePlainImageLabelDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<float> *img_content = nullptr,
    const std::vector<float> *label_content = nullptr) {
  auto img_content__ = img_content ? _fbb.CreateVector<float>(*img_content) : 0;
  auto label_content__ = label_content ? _fbb.CreateVector<float>(*label_content) : 0;
  return CreatePlainImageLabel(
      _fbb,
      img_content__,
      label_content__);
}

inline const PlainImageLabel *GetPlainImageLabel(const void *buf) {
  return flatbuffers::GetRoot<PlainImageLabel>(buf);
}

inline const PlainImageLabel *GetSizePrefixedPlainImageLabel(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<PlainImageLabel>(buf);
}

inline PlainImageLabel *GetMutablePlainImageLabel(void *buf) {
  return flatbuffers::GetMutableRoot<PlainImageLabel>(buf);
}

inline PlainImageLabel *GetMutableSizePrefixedPlainImageLabel(void *buf) {
  return flatbuffers::GetMutableSizePrefixedRoot<PlainImageLabel>(buf);
}

inline bool VerifyPlainImageLabelBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<PlainImageLabel>(nullptr);
}

inline bool VerifySizePrefixedPlainImageLabelBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<PlainImageLabel>(nullptr);
}

inline void FinishPlainImageLabelBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<PlainImageLabel> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedPlainImageLabelBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<PlainImageLabel> root) {
  fbb.FinishSizePrefixed(root);
}

#endif  // FLATBUFFERS_GENERATED_PLAINIMAGELABEL_H_
