// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PLAINLABEL_H_
#define FLATBUFFERS_GENERATED_PLAINLABEL_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 22 &&
              FLATBUFFERS_VERSION_MINOR == 11 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

struct PlainLabel;
struct PlainLabelBuilder;

struct PlainLabel FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef PlainLabelBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_LABEL_CONTENT = 4
  };
  const flatbuffers::Vector<float> *label_content() const {
    return GetPointer<const flatbuffers::Vector<float> *>(VT_LABEL_CONTENT);
  }
  flatbuffers::Vector<float> *mutable_label_content() {
    return GetPointer<flatbuffers::Vector<float> *>(VT_LABEL_CONTENT);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_LABEL_CONTENT) &&
           verifier.VerifyVector(label_content()) &&
           verifier.EndTable();
  }
};

struct PlainLabelBuilder {
  typedef PlainLabel Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_label_content(flatbuffers::Offset<flatbuffers::Vector<float>> label_content) {
    fbb_.AddOffset(PlainLabel::VT_LABEL_CONTENT, label_content);
  }
  explicit PlainLabelBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<PlainLabel> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<PlainLabel>(end);
    fbb_.Required(o, PlainLabel::VT_LABEL_CONTENT);
    return o;
  }
};

inline flatbuffers::Offset<PlainLabel> CreatePlainLabel(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<float>> label_content = 0) {
  PlainLabelBuilder builder_(_fbb);
  builder_.add_label_content(label_content);
  return builder_.Finish();
}

inline flatbuffers::Offset<PlainLabel> CreatePlainLabelDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<float> *label_content = nullptr) {
  auto label_content__ = label_content ? _fbb.CreateVector<float>(*label_content) : 0;
  return CreatePlainLabel(
      _fbb,
      label_content__);
}

inline const PlainLabel *GetPlainLabel(const void *buf) {
  return flatbuffers::GetRoot<PlainLabel>(buf);
}

inline const PlainLabel *GetSizePrefixedPlainLabel(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<PlainLabel>(buf);
}

inline PlainLabel *GetMutablePlainLabel(void *buf) {
  return flatbuffers::GetMutableRoot<PlainLabel>(buf);
}

inline PlainLabel *GetMutableSizePrefixedPlainLabel(void *buf) {
  return flatbuffers::GetMutableSizePrefixedRoot<PlainLabel>(buf);
}

inline bool VerifyPlainLabelBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<PlainLabel>(nullptr);
}

inline bool VerifySizePrefixedPlainLabelBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<PlainLabel>(nullptr);
}

inline void FinishPlainLabelBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<PlainLabel> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedPlainLabelBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<PlainLabel> root) {
  fbb.FinishSizePrefixed(root);
}

#endif  // FLATBUFFERS_GENERATED_PLAINLABEL_H_
