// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SINGLEUNITPARAMSET_H_
#define FLATBUFFERS_GENERATED_SINGLEUNITPARAMSET_H_

#include "flatbuffers/flatbuffers.h"

struct SingleUnitParamSet;
struct SingleUnitParamSetT;

inline const flatbuffers::TypeTable *SingleUnitParamSetTypeTable();

struct SingleUnitParamSetT : public flatbuffers::NativeTable {
  typedef SingleUnitParamSet TableType;
  std::vector<float> param_content;
  SingleUnitParamSetT() {
  }
};

struct SingleUnitParamSet FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef SingleUnitParamSetT NativeTableType;
  static const flatbuffers::TypeTable *MiniReflectTypeTable() {
    return SingleUnitParamSetTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PARAM_CONTENT = 4
  };
  const flatbuffers::Vector<float> *param_content() const {
    return GetPointer<const flatbuffers::Vector<float> *>(VT_PARAM_CONTENT);
  }
  flatbuffers::Vector<float> *mutable_param_content() {
    return GetPointer<flatbuffers::Vector<float> *>(VT_PARAM_CONTENT);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_PARAM_CONTENT) &&
           verifier.VerifyVector(param_content()) &&
           verifier.EndTable();
  }
  SingleUnitParamSetT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(SingleUnitParamSetT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<SingleUnitParamSet> Pack(flatbuffers::FlatBufferBuilder &_fbb, const SingleUnitParamSetT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct SingleUnitParamSetBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_param_content(flatbuffers::Offset<flatbuffers::Vector<float>> param_content) {
    fbb_.AddOffset(SingleUnitParamSet::VT_PARAM_CONTENT, param_content);
  }
  explicit SingleUnitParamSetBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  SingleUnitParamSetBuilder &operator=(const SingleUnitParamSetBuilder &);
  flatbuffers::Offset<SingleUnitParamSet> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<SingleUnitParamSet>(end);
    fbb_.Required(o, SingleUnitParamSet::VT_PARAM_CONTENT);
    return o;
  }
};

inline flatbuffers::Offset<SingleUnitParamSet> CreateSingleUnitParamSet(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<float>> param_content = 0) {
  SingleUnitParamSetBuilder builder_(_fbb);
  builder_.add_param_content(param_content);
  return builder_.Finish();
}

inline flatbuffers::Offset<SingleUnitParamSet> CreateSingleUnitParamSetDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<float> *param_content = nullptr) {
  auto param_content__ = param_content ? _fbb.CreateVector<float>(*param_content) : 0;
  return CreateSingleUnitParamSet(
      _fbb,
      param_content__);
}

flatbuffers::Offset<SingleUnitParamSet> CreateSingleUnitParamSet(flatbuffers::FlatBufferBuilder &_fbb, const SingleUnitParamSetT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline SingleUnitParamSetT *SingleUnitParamSet::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  auto _o = new SingleUnitParamSetT();
  UnPackTo(_o, _resolver);
  return _o;
}

inline void SingleUnitParamSet::UnPackTo(SingleUnitParamSetT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = param_content(); if (_e) { _o->param_content.resize(_e->size()); for (flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->param_content[_i] = _e->Get(_i); } } }
}

inline flatbuffers::Offset<SingleUnitParamSet> SingleUnitParamSet::Pack(flatbuffers::FlatBufferBuilder &_fbb, const SingleUnitParamSetT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateSingleUnitParamSet(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<SingleUnitParamSet> CreateSingleUnitParamSet(flatbuffers::FlatBufferBuilder &_fbb, const SingleUnitParamSetT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const SingleUnitParamSetT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _param_content = _fbb.CreateVector(_o->param_content);
  return CreateSingleUnitParamSet(
      _fbb,
      _param_content);
}

inline const flatbuffers::TypeTable *SingleUnitParamSetTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_FLOAT, 1, -1 }
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_TABLE, 1, type_codes, nullptr, nullptr, nullptr
  };
  return &tt;
}

inline const SingleUnitParamSet *GetSingleUnitParamSet(const void *buf) {
  return flatbuffers::GetRoot<SingleUnitParamSet>(buf);
}

inline const SingleUnitParamSet *GetSizePrefixedSingleUnitParamSet(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<SingleUnitParamSet>(buf);
}

inline SingleUnitParamSet *GetMutableSingleUnitParamSet(void *buf) {
  return flatbuffers::GetMutableRoot<SingleUnitParamSet>(buf);
}

inline bool VerifySingleUnitParamSetBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<SingleUnitParamSet>(nullptr);
}

inline bool VerifySizePrefixedSingleUnitParamSetBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<SingleUnitParamSet>(nullptr);
}

inline void FinishSingleUnitParamSetBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<SingleUnitParamSet> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedSingleUnitParamSetBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<SingleUnitParamSet> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<SingleUnitParamSetT> UnPackSingleUnitParamSet(
    const void *buf,
    const flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<SingleUnitParamSetT>(GetSingleUnitParamSet(buf)->UnPack(res));
}

inline std::unique_ptr<SingleUnitParamSetT> UnPackSizePrefixedSingleUnitParamSet(
    const void *buf,
    const flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<SingleUnitParamSetT>(GetSizePrefixedSingleUnitParamSet(buf)->UnPack(res));
}

#endif  // FLATBUFFERS_GENERATED_SINGLEUNITPARAMSET_H_
