// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SINGLEUNITPARAMSET_H_
#define FLATBUFFERS_GENERATED_SINGLEUNITPARAMSET_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 22 &&
              FLATBUFFERS_VERSION_MINOR == 11 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

struct SingleUnitParamSet;
struct SingleUnitParamSetBuilder;

struct SingleUnitParamSet FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef SingleUnitParamSetBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PARAM_CONTENT = 4
  };
  const flatbuffers::Vector<float> *param_content() const {
    return GetPointer<const flatbuffers::Vector<float> *>(VT_PARAM_CONTENT);
  }
  flatbuffers::Vector<float> *mutable_param_content() {
    return GetPointer<flatbuffers::Vector<float> *>(VT_PARAM_CONTENT);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_PARAM_CONTENT) &&
           verifier.VerifyVector(param_content()) &&
           verifier.EndTable();
  }
};

struct SingleUnitParamSetBuilder {
  typedef SingleUnitParamSet Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_param_content(flatbuffers::Offset<flatbuffers::Vector<float>> param_content) {
    fbb_.AddOffset(SingleUnitParamSet::VT_PARAM_CONTENT, param_content);
  }
  explicit SingleUnitParamSetBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<SingleUnitParamSet> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<SingleUnitParamSet>(end);
    fbb_.Required(o, SingleUnitParamSet::VT_PARAM_CONTENT);
    return o;
  }
};

inline flatbuffers::Offset<SingleUnitParamSet> CreateSingleUnitParamSet(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<float>> param_content = 0) {
  SingleUnitParamSetBuilder builder_(_fbb);
  builder_.add_param_content(param_content);
  return builder_.Finish();
}

inline flatbuffers::Offset<SingleUnitParamSet> CreateSingleUnitParamSetDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<float> *param_content = nullptr) {
  auto param_content__ = param_content ? _fbb.CreateVector<float>(*param_content) : 0;
  return CreateSingleUnitParamSet(
      _fbb,
      param_content__);
}

inline const SingleUnitParamSet *GetSingleUnitParamSet(const void *buf) {
  return flatbuffers::GetRoot<SingleUnitParamSet>(buf);
}

inline const SingleUnitParamSet *GetSizePrefixedSingleUnitParamSet(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<SingleUnitParamSet>(buf);
}

inline SingleUnitParamSet *GetMutableSingleUnitParamSet(void *buf) {
  return flatbuffers::GetMutableRoot<SingleUnitParamSet>(buf);
}

inline SingleUnitParamSet *GetMutableSizePrefixedSingleUnitParamSet(void *buf) {
  return flatbuffers::GetMutableSizePrefixedRoot<SingleUnitParamSet>(buf);
}

inline bool VerifySingleUnitParamSetBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<SingleUnitParamSet>(nullptr);
}

inline bool VerifySizePrefixedSingleUnitParamSetBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<SingleUnitParamSet>(nullptr);
}

inline void FinishSingleUnitParamSetBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<SingleUnitParamSet> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedSingleUnitParamSetBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<SingleUnitParamSet> root) {
  fbb.FinishSizePrefixed(root);
}

#endif  // FLATBUFFERS_GENERATED_SINGLEUNITPARAMSET_H_
