#pragma once
#ifndef _TRUSTED_CONFIG_H
#define _TRUSTED_CONFIG_H

#define ALLOW_TIMING_REPORT

#define SGX_CONV_BATCH_PRECOMPUTE_VERIFY

#define SGX_FAST_TWEAKS_SKIP_DS_VERIFICATION

#define SGX_FAST_TWEAKS_SMALLER_INITEGRIRTY_RATE

#define SGX_FAST_TWEAKS_NO_MEMSET

/* #undef SGX_USE_BLASFEO_GEMV */

/* #undef SGX_RMM_ADD_NOISE_CONV_WEIGHTS_CHECK_VERIFICATION_FAILS */

// Enclave heap configurations
#define SGX_AVIALABLE_HEAP_MAX_MB (256)
#define SGX_AVIALABLE_HEAP_MIN_MB (85)
#define SGX_AVIALABLE_HEAP_INIT_MB (256)

#endif //_TRUSTED_CONFIG_H
