#pragma once
#ifndef _TRUSTED_CONFIG_H
#define _TRUSTED_CONFIG_H

#define ALLOW_TIMING_REPORT

#define SGX_CONV_BATCH_PRECOMPUTE_VERIFY

#define SGX_FAST_TWEAKS_SKIP_DS_VERIFICATION

#define SGX_FAST_TWEAKS_SMALLER_INITEGRIRTY_RATE

/* #undef SGX_USE_BLASFEO_GEMV */

/* #undef SGX_RMM_ADD_NOISE_CONV_WEIGHTS_CHECK_VERIFICATION_FAILS */

#endif //_TRUSTED_CONFIG_H
